// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420102544_check")]
    partial class check
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("AppointmentEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AppointmentStart")
                        .HasColumnType("time");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernateId = 1,
                            Name = "المعادي"
                        },
                        new
                        {
                            Id = 2,
                            GovernateId = 1,
                            Name = "مدينة نصر"
                        },
                        new
                        {
                            Id = 3,
                            GovernateId = 1,
                            Name = "مصر الجديدة"
                        },
                        new
                        {
                            Id = 4,
                            GovernateId = 1,
                            Name = "الزمالك"
                        },
                        new
                        {
                            Id = 5,
                            GovernateId = 1,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 6,
                            GovernateId = 1,
                            Name = "العباسية"
                        },
                        new
                        {
                            Id = 7,
                            GovernateId = 1,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 8,
                            GovernateId = 2,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 9,
                            GovernateId = 2,
                            Name = "الدقي"
                        },
                        new
                        {
                            Id = 10,
                            GovernateId = 2,
                            Name = "العجوزة"
                        },
                        new
                        {
                            Id = 11,
                            GovernateId = 2,
                            Name = "المهندسين"
                        },
                        new
                        {
                            Id = 12,
                            GovernateId = 3,
                            Name = "سموحة"
                        },
                        new
                        {
                            Id = 13,
                            GovernateId = 3,
                            Name = "محطة الرمل"
                        },
                        new
                        {
                            Id = 14,
                            GovernateId = 3,
                            Name = "العصافرة"
                        },
                        new
                        {
                            Id = 15,
                            GovernateId = 3,
                            Name = "السان استيفانو"
                        },
                        new
                        {
                            Id = 16,
                            GovernateId = 4,
                            Name = "المنصورة"
                        },
                        new
                        {
                            Id = 17,
                            GovernateId = 4,
                            Name = "طلخا"
                        },
                        new
                        {
                            Id = 18,
                            GovernateId = 4,
                            Name = "ميت غمر"
                        },
                        new
                        {
                            Id = 19,
                            GovernateId = 5,
                            Name = "الغردقة"
                        },
                        new
                        {
                            Id = 20,
                            GovernateId = 5,
                            Name = "رأس غارب"
                        },
                        new
                        {
                            Id = 21,
                            GovernateId = 5,
                            Name = "سفاجا"
                        },
                        new
                        {
                            Id = 22,
                            GovernateId = 6,
                            Name = "دمنهور"
                        },
                        new
                        {
                            Id = 23,
                            GovernateId = 6,
                            Name = "كفر الدوار"
                        },
                        new
                        {
                            Id = 24,
                            GovernateId = 6,
                            Name = "إيتاي البارود"
                        },
                        new
                        {
                            Id = 25,
                            GovernateId = 7,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 26,
                            GovernateId = 7,
                            Name = "سنورس"
                        },
                        new
                        {
                            Id = 27,
                            GovernateId = 7,
                            Name = "طامية"
                        },
                        new
                        {
                            Id = 28,
                            GovernateId = 8,
                            Name = "طنطا"
                        },
                        new
                        {
                            Id = 29,
                            GovernateId = 8,
                            Name = "المحلة الكبرى"
                        },
                        new
                        {
                            Id = 30,
                            GovernateId = 8,
                            Name = "كفر الزيات"
                        },
                        new
                        {
                            Id = 31,
                            GovernateId = 9,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            Id = 32,
                            GovernateId = 9,
                            Name = "فايد"
                        },
                        new
                        {
                            Id = 33,
                            GovernateId = 9,
                            Name = "القنطرة شرق"
                        },
                        new
                        {
                            Id = 34,
                            GovernateId = 10,
                            Name = "شبين الكوم"
                        },
                        new
                        {
                            Id = 35,
                            GovernateId = 10,
                            Name = "منوف"
                        },
                        new
                        {
                            Id = 36,
                            GovernateId = 10,
                            Name = "أشمون"
                        },
                        new
                        {
                            Id = 37,
                            GovernateId = 11,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 38,
                            GovernateId = 11,
                            Name = "ملوي"
                        },
                        new
                        {
                            Id = 39,
                            GovernateId = 11,
                            Name = "أبوقرقاص"
                        },
                        new
                        {
                            Id = 40,
                            GovernateId = 12,
                            Name = "بنها"
                        },
                        new
                        {
                            Id = 41,
                            GovernateId = 12,
                            Name = "قليوب"
                        },
                        new
                        {
                            Id = 42,
                            GovernateId = 12,
                            Name = "شبرا الخيمة"
                        });
                });

            modelBuilder.Entity("DAL.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("SpecialityId");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("DAL.Models.DoctorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("AppointmentEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AppointmentStart")
                        .HasColumnType("time");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");
                });

            modelBuilder.Entity("DAL.Models.Governate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الأسكندرية"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            Id = 5,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            Id = 6,
                            Name = "البحيرة"
                        },
                        new
                        {
                            Id = 7,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 8,
                            Name = "الغربية"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الإسماعلية"
                        },
                        new
                        {
                            Id = 10,
                            Name = "المنوفية"
                        },
                        new
                        {
                            Id = 11,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 12,
                            Name = "القليوبية"
                        },
                        new
                        {
                            Id = 13,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            Id = 14,
                            Name = "السويس"
                        },
                        new
                        {
                            Id = 15,
                            Name = "اسوان"
                        },
                        new
                        {
                            Id = 16,
                            Name = "اسيوط"
                        },
                        new
                        {
                            Id = 17,
                            Name = "بني سويف"
                        },
                        new
                        {
                            Id = 18,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            Id = 19,
                            Name = "دمياط"
                        },
                        new
                        {
                            Id = 20,
                            Name = "الشرقية"
                        },
                        new
                        {
                            Id = 21,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            Id = 22,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            Id = 23,
                            Name = "مطروح"
                        },
                        new
                        {
                            Id = 24,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 25,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 26,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            Id = 27,
                            Name = "سوهاج"
                        });
                });

            modelBuilder.Entity("DAL.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("GovernateId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernateId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DAL.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "أخصائي حساسية/مناعة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "أخصائي تخدير"
                        },
                        new
                        {
                            Id = 3,
                            Name = "أخصائي قلب"
                        },
                        new
                        {
                            Id = 4,
                            Name = "أخصائي جلدية"
                        },
                        new
                        {
                            Id = 5,
                            Name = "أخصائي غدد صماء"
                        },
                        new
                        {
                            Id = 6,
                            Name = "أخصائي جهاز هضمي"
                        },
                        new
                        {
                            Id = 7,
                            Name = "طبيب عام"
                        },
                        new
                        {
                            Id = 8,
                            Name = "أخصائي طب كبار السن"
                        },
                        new
                        {
                            Id = 9,
                            Name = "أخصائي دم"
                        },
                        new
                        {
                            Id = 10,
                            Name = "أخصائي أمراض معدية"
                        },
                        new
                        {
                            Id = 11,
                            Name = "طبيب باطنية"
                        },
                        new
                        {
                            Id = 12,
                            Name = "أخصائي كلى"
                        },
                        new
                        {
                            Id = 13,
                            Name = "أخصائي أعصاب"
                        },
                        new
                        {
                            Id = 14,
                            Name = "أخصائي نساء وتوليد"
                        },
                        new
                        {
                            Id = 15,
                            Name = "أخصائي أورام"
                        },
                        new
                        {
                            Id = 16,
                            Name = "أخصائي عيون"
                        },
                        new
                        {
                            Id = 17,
                            Name = "جراح عظام"
                        },
                        new
                        {
                            Id = 18,
                            Name = "أخصائي أنف وأذن وحنجرة"
                        },
                        new
                        {
                            Id = 19,
                            Name = "أخصائي أمراض"
                        },
                        new
                        {
                            Id = 20,
                            Name = "أخصائي أطفال"
                        },
                        new
                        {
                            Id = 21,
                            Name = "جراح تجميل"
                        },
                        new
                        {
                            Id = 22,
                            Name = "أخصائي نفسية"
                        },
                        new
                        {
                            Id = 23,
                            Name = "أخصائي صدر"
                        },
                        new
                        {
                            Id = 24,
                            Name = "أخصائي أشعة"
                        },
                        new
                        {
                            Id = 25,
                            Name = "أخصائي روماتيزم"
                        },
                        new
                        {
                            Id = 26,
                            Name = "جراح عام"
                        },
                        new
                        {
                            Id = 27,
                            Name = "أخصائي مسالك بولية"
                        });
                });

            modelBuilder.Entity("DAL.Models.Appointment", b =>
                {
                    b.HasOne("DAL.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.HasOne("DAL.Models.Governate", "Governate")
                        .WithMany()
                        .HasForeignKey("GovernateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("DAL.Models.Clinic", b =>
                {
                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Location");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.HasOne("DAL.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DAL.Models.DoctorAvailability", b =>
                {
                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DAL.Models.Location", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Governate", "Governate")
                        .WithMany()
                        .HasForeignKey("GovernateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
