// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615014737_AddedSomeSeedDatav03")]
    partial class AddedSomeSeedDatav03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("AppointmentEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AppointmentStart")
                        .HasColumnType("time");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GovernateId = 1,
                            Name = "المعادي"
                        },
                        new
                        {
                            Id = 2,
                            GovernateId = 1,
                            Name = "مدينة نصر"
                        },
                        new
                        {
                            Id = 3,
                            GovernateId = 1,
                            Name = "مصر الجديدة"
                        },
                        new
                        {
                            Id = 4,
                            GovernateId = 1,
                            Name = "الزمالك"
                        },
                        new
                        {
                            Id = 5,
                            GovernateId = 1,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 6,
                            GovernateId = 1,
                            Name = "العباسية"
                        },
                        new
                        {
                            Id = 7,
                            GovernateId = 1,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 8,
                            GovernateId = 2,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 9,
                            GovernateId = 2,
                            Name = "الدقي"
                        },
                        new
                        {
                            Id = 10,
                            GovernateId = 2,
                            Name = "العجوزة"
                        },
                        new
                        {
                            Id = 11,
                            GovernateId = 2,
                            Name = "المهندسين"
                        },
                        new
                        {
                            Id = 12,
                            GovernateId = 3,
                            Name = "سموحة"
                        },
                        new
                        {
                            Id = 13,
                            GovernateId = 3,
                            Name = "محطة الرمل"
                        },
                        new
                        {
                            Id = 14,
                            GovernateId = 3,
                            Name = "العصافرة"
                        },
                        new
                        {
                            Id = 15,
                            GovernateId = 3,
                            Name = "السان استيفانو"
                        },
                        new
                        {
                            Id = 16,
                            GovernateId = 4,
                            Name = "المنصورة"
                        },
                        new
                        {
                            Id = 17,
                            GovernateId = 4,
                            Name = "طلخا"
                        },
                        new
                        {
                            Id = 18,
                            GovernateId = 4,
                            Name = "ميت غمر"
                        },
                        new
                        {
                            Id = 19,
                            GovernateId = 5,
                            Name = "الغردقة"
                        },
                        new
                        {
                            Id = 20,
                            GovernateId = 5,
                            Name = "رأس غارب"
                        },
                        new
                        {
                            Id = 21,
                            GovernateId = 5,
                            Name = "سفاجا"
                        },
                        new
                        {
                            Id = 22,
                            GovernateId = 6,
                            Name = "دمنهور"
                        },
                        new
                        {
                            Id = 23,
                            GovernateId = 6,
                            Name = "كفر الدوار"
                        },
                        new
                        {
                            Id = 24,
                            GovernateId = 6,
                            Name = "إيتاي البارود"
                        },
                        new
                        {
                            Id = 25,
                            GovernateId = 7,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 26,
                            GovernateId = 7,
                            Name = "سنورس"
                        },
                        new
                        {
                            Id = 27,
                            GovernateId = 7,
                            Name = "طامية"
                        },
                        new
                        {
                            Id = 28,
                            GovernateId = 8,
                            Name = "طنطا"
                        },
                        new
                        {
                            Id = 29,
                            GovernateId = 8,
                            Name = "المحلة الكبرى"
                        },
                        new
                        {
                            Id = 30,
                            GovernateId = 8,
                            Name = "كفر الزيات"
                        },
                        new
                        {
                            Id = 31,
                            GovernateId = 9,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            Id = 32,
                            GovernateId = 9,
                            Name = "فايد"
                        },
                        new
                        {
                            Id = 33,
                            GovernateId = 9,
                            Name = "القنطرة شرق"
                        },
                        new
                        {
                            Id = 34,
                            GovernateId = 10,
                            Name = "شبين الكوم"
                        },
                        new
                        {
                            Id = 35,
                            GovernateId = 10,
                            Name = "منوف"
                        },
                        new
                        {
                            Id = 36,
                            GovernateId = 10,
                            Name = "أشمون"
                        },
                        new
                        {
                            Id = 37,
                            GovernateId = 11,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 38,
                            GovernateId = 11,
                            Name = "ملوي"
                        },
                        new
                        {
                            Id = 39,
                            GovernateId = 11,
                            Name = "أبوقرقاص"
                        },
                        new
                        {
                            Id = 40,
                            GovernateId = 12,
                            Name = "بنها"
                        },
                        new
                        {
                            Id = 41,
                            GovernateId = 12,
                            Name = "قليوب"
                        },
                        new
                        {
                            Id = 42,
                            GovernateId = 12,
                            Name = "شبرا الخيمة"
                        });
                });

            modelBuilder.Entity("DAL.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            LocationId = 1,
                            Name = "Heart Care Clinic",
                            Phone = "01010010001",
                            Price = 500m,
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            LocationId = 2,
                            Name = "Kids Health Clinic",
                            Phone = "01010010002",
                            Price = 350m,
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            LocationId = 3,
                            Name = "Surgical Center",
                            Phone = "01010010003",
                            Price = 600m,
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 4,
                            LocationId = 4,
                            Name = "Skin Wellness Clinic",
                            Phone = "01010010004",
                            Price = 400m,
                            SpecialityId = 4
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 5,
                            LocationId = 5,
                            Name = "Neuro Center",
                            Phone = "01010010005",
                            Price = 550m,
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 6,
                            LocationId = 6,
                            Name = "Women's Health Clinic",
                            Phone = "01010010006",
                            Price = 500m,
                            SpecialityId = 6
                        },
                        new
                        {
                            Id = 7,
                            DoctorId = 7,
                            LocationId = 7,
                            Name = "Ortho Move Clinic",
                            Phone = "01010010007",
                            Price = 340m,
                            SpecialityId = 7
                        },
                        new
                        {
                            Id = 8,
                            DoctorId = 8,
                            LocationId = 8,
                            Name = "Chronic Care Clinic",
                            Phone = "01010010008",
                            Price = 300m,
                            SpecialityId = 8
                        },
                        new
                        {
                            Id = 9,
                            DoctorId = 9,
                            LocationId = 9,
                            Name = "Mind Matters Clinic",
                            Phone = "01010010009",
                            Price = 450m,
                            SpecialityId = 9
                        },
                        new
                        {
                            Id = 10,
                            DoctorId = 10,
                            LocationId = 10,
                            Name = "Vision Center",
                            Phone = "01010010010",
                            Price = 500m,
                            SpecialityId = 10
                        },
                        new
                        {
                            Id = 11,
                            DoctorId = 11,
                            LocationId = 11,
                            Name = "ENT Specialists",
                            Phone = "01010010011",
                            Price = 400m,
                            SpecialityId = 11
                        },
                        new
                        {
                            Id = 12,
                            DoctorId = 12,
                            LocationId = 12,
                            Name = "Pathology Lab",
                            Phone = "01010010012",
                            Price = 300m,
                            SpecialityId = 12
                        },
                        new
                        {
                            Id = 13,
                            DoctorId = 13,
                            LocationId = 13,
                            Name = "Endocrine Experts",
                            Phone = "01010010013",
                            Price = 450m,
                            SpecialityId = 13
                        },
                        new
                        {
                            Id = 14,
                            DoctorId = 14,
                            LocationId = 14,
                            Name = "Autoimmune Center",
                            Phone = "01010010014",
                            Price = 470m,
                            SpecialityId = 14
                        },
                        new
                        {
                            Id = 15,
                            DoctorId = 15,
                            LocationId = 15,
                            Name = "Kidney Care Clinic",
                            Phone = "01010010015",
                            Price = 480m,
                            SpecialityId = 15
                        },
                        new
                        {
                            Id = 16,
                            DoctorId = 16,
                            LocationId = 16,
                            Name = "Blood Center",
                            Phone = "01010010016",
                            Price = 500m,
                            SpecialityId = 16
                        },
                        new
                        {
                            Id = 17,
                            DoctorId = 17,
                            LocationId = 17,
                            Name = "Digestive Health Clinic",
                            Phone = "01010010017",
                            Price = 460m,
                            SpecialityId = 17
                        },
                        new
                        {
                            Id = 18,
                            DoctorId = 18,
                            LocationId = 18,
                            Name = "Family Health Clinic",
                            Phone = "01010010018",
                            Price = 350m,
                            SpecialityId = 18
                        },
                        new
                        {
                            Id = 19,
                            DoctorId = 19,
                            LocationId = 19,
                            Name = "Lung & Breathing Clinic",
                            Phone = "01010010019",
                            Price = 430m,
                            SpecialityId = 19
                        },
                        new
                        {
                            Id = 20,
                            DoctorId = 20,
                            LocationId = 20,
                            Name = "Cancer Treatment Center",
                            Phone = "01010010020",
                            Price = 400m,
                            SpecialityId = 20
                        },
                        new
                        {
                            Id = 21,
                            DoctorId = 21,
                            LocationId = 21,
                            Name = "Imaging Center",
                            Phone = "01010010021",
                            Price = 300m,
                            SpecialityId = 21
                        },
                        new
                        {
                            Id = 22,
                            DoctorId = 22,
                            LocationId = 22,
                            Name = "Anesthesia Services",
                            Phone = "01010010022",
                            Price = 200m,
                            SpecialityId = 22
                        },
                        new
                        {
                            Id = 23,
                            DoctorId = 23,
                            LocationId = 23,
                            Name = "Smile Dental Clinic",
                            Phone = "01010010023",
                            Price = 400m,
                            SpecialityId = 23
                        },
                        new
                        {
                            Id = 24,
                            DoctorId = 24,
                            LocationId = 24,
                            Name = "Uro Care Center",
                            Phone = "01010010024",
                            Price = 380m,
                            SpecialityId = 24
                        },
                        new
                        {
                            Id = 25,
                            DoctorId = 25,
                            LocationId = 25,
                            Name = "Beauty & Reconstruction",
                            Phone = "01010010025",
                            Price = 750m,
                            SpecialityId = 25
                        },
                        new
                        {
                            Id = 26,
                            DoctorId = 26,
                            LocationId = 26,
                            Name = "Vascular Solutions",
                            Phone = "01010010026",
                            Price = 350m,
                            SpecialityId = 26
                        },
                        new
                        {
                            Id = 27,
                            DoctorId = 27,
                            LocationId = 27,
                            Name = "Fertility Center",
                            Phone = "01010010027",
                            Price = 450m,
                            SpecialityId = 27
                        },
                        new
                        {
                            Id = 28,
                            DoctorId = 28,
                            LocationId = 28,
                            Name = "Neighborhood GP Clinic",
                            Phone = "01010010028",
                            Price = 300m,
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 29,
                            DoctorId = 29,
                            LocationId = 29,
                            Name = "Little Stars Pediatrics",
                            Phone = "01010010029",
                            Price = 370m,
                            SpecialityId = 6
                        },
                        new
                        {
                            Id = 30,
                            DoctorId = 30,
                            LocationId = 30,
                            Name = "Critical Care Hub",
                            Phone = "01010010030",
                            Price = 320m,
                            SpecialityId = 7
                        });
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("SpecialityId");

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Dr. Ahmed Samir is a seasoned cardiologist with over 15 years of experience. He is well-known for his expertise in treating complex heart conditions and his dedication to preventative care.",
                            Email = "ahmed.samir@example.com",
                            FirstName = "Ahmed",
                            LastName = "Samir",
                            Password = "hashedpassword1",
                            Phone = "01012345678",
                            Rate = 4.5999999999999996,
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 2,
                            About = "Dr. Nour Hassan is a passionate pediatrician who excels in creating a friendly and comfortable environment for children while providing high-quality medical care.",
                            Email = "nour.hassan@example.com",
                            FirstName = "Nour",
                            LastName = "Hassan",
                            Password = "hashedpassword2",
                            Phone = "01123456789",
                            Rate = 4.7000000000000002,
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 3,
                            About = "Dr. Youssef Mahmoud is a general surgeon with vast experience in minimally invasive surgical techniques and postoperative care.",
                            Email = "youssef.mahmoud@example.com",
                            FirstName = "Youssef",
                            LastName = "Mahmoud",
                            Password = "hashedpassword3",
                            Phone = "01234567890",
                            Rate = 4.7999999999999998,
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 4,
                            About = "Dr. Fatma Amin is a skilled dermatologist who specializes in treating chronic skin conditions and offers a blend of clinical and aesthetic dermatology.",
                            Email = "fatma.amin@example.com",
                            FirstName = "Fatma",
                            LastName = "Amin",
                            Password = "hashedpassword4",
                            Phone = "01587654321",
                            Rate = 4.2999999999999998,
                            SpecialityId = 4
                        },
                        new
                        {
                            Id = 5,
                            About = "Dr. Omar Hassan is a neurologist with deep expertise in treating epilepsy, migraines, and nervous system disorders. He provides comprehensive evaluations and long-term management plans.",
                            Email = "omar.hassan@example.com",
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Password = "hashedpassword5",
                            Phone = "01098765432",
                            Rate = 4.2000000000000002,
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 6,
                            About = "Dr. Salma Mostafa is a gynecologist who focuses on women's health and reproductive issues. She is widely respected for her compassionate approach and surgical skill.",
                            Email = "salma.mostafa@example.com",
                            FirstName = "Salma",
                            LastName = "Mostafa",
                            Password = "hashedpassword6",
                            Phone = "01155667718",
                            Rate = 4.4000000000000004,
                            SpecialityId = 6
                        },
                        new
                        {
                            Id = 7,
                            About = "Dr. Mohamed Adel is an orthopedic surgeon with a focus on joint replacement and sports injuries. He’s known for helping patients regain mobility with effective treatments.",
                            Email = "mohamed.adel@example.com",
                            FirstName = "Mohamed",
                            LastName = "Adel",
                            Password = "hashedpassword7",
                            Phone = "01266778199",
                            Rate = 4.5,
                            SpecialityId = 7
                        },
                        new
                        {
                            Id = 8,
                            About = "Dr. Rania Saad is an internist providing expert care in chronic conditions such as diabetes, hypertension, and gastrointestinal diseases.",
                            Email = "rania.saad@example.com",
                            FirstName = "Rania",
                            LastName = "Saad",
                            Password = "hashedpassword8",
                            Phone = "01599887766",
                            Rate = 4.0999999999999996,
                            SpecialityId = 8
                        },
                        new
                        {
                            Id = 9,
                            About = "Dr. Hossam Yehia is a psychiatrist with a strong reputation in treating mood and anxiety disorders through both therapy and medication.",
                            Email = "hossam.yehia@example.com",
                            FirstName = "Hossam",
                            LastName = "Yehia",
                            Password = "hashedpassword9",
                            Phone = "01022334455",
                            Rate = 4.0,
                            SpecialityId = 9
                        },
                        new
                        {
                            Id = 10,
                            About = "Dr. Dina Ibrahim is an ophthalmologist skilled in laser eye surgery and glaucoma management. Her detail-oriented care has helped many regain vision.",
                            Email = "dina.ibrahim@example.com",
                            FirstName = "Dina",
                            LastName = "Ibrahim",
                            Password = "hashedpassword10",
                            Phone = "01144556677",
                            Rate = 4.9000000000000004,
                            SpecialityId = 10
                        },
                        new
                        {
                            Id = 11,
                            About = "Dr. Ali Khaled is an ENT specialist who offers comprehensive care for sinus disorders, hearing loss, and voice disorders.",
                            Email = "ali.khaled@example.com",
                            FirstName = "Ali",
                            LastName = "Khaled",
                            Password = "hashedpassword11",
                            Phone = "01233445566",
                            Rate = 4.2999999999999998,
                            SpecialityId = 11
                        },
                        new
                        {
                            Id = 12,
                            About = "Dr. Nada Zaki is a clinical pathologist with a keen interest in hematology and diagnostics. She ensures precise and timely lab results for better diagnosis.",
                            Email = "nada.zaki@example.com",
                            FirstName = "Nada",
                            LastName = "Zaki",
                            Password = "hashedpassword12",
                            Phone = "01511223344",
                            Rate = 4.5999999999999996,
                            SpecialityId = 12
                        },
                        new
                        {
                            Id = 13,
                            About = "Dr. Karim Osman is an endocrinologist specializing in thyroid disorders, diabetes, and metabolic conditions. He combines technology and personal care.",
                            Email = "karim.osman@example.com",
                            FirstName = "Karim",
                            LastName = "Osman",
                            Password = "hashedpassword13",
                            Phone = "01033445566",
                            Rate = 4.7000000000000002,
                            SpecialityId = 13
                        },
                        new
                        {
                            Id = 14,
                            About = "Dr. Layla Nasser is a rheumatologist with extensive experience in treating autoimmune diseases such as lupus and rheumatoid arthritis.",
                            Email = "layla.nasser@example.com",
                            FirstName = "Layla",
                            LastName = "Nasser",
                            Password = "hashedpassword14",
                            Phone = "01199887766",
                            Rate = 4.7999999999999998,
                            SpecialityId = 14
                        },
                        new
                        {
                            Id = 15,
                            About = "Dr. Tamer ElSayed is a nephrologist who manages patients with kidney failure and provides dialysis care in both acute and chronic settings.",
                            Email = "tamer.elsayed@example.com",
                            FirstName = "Tamer",
                            LastName = "ElSayed",
                            Password = "hashedpassword15",
                            Phone = "01277889900",
                            Rate = 4.5,
                            SpecialityId = 15
                        },
                        new
                        {
                            Id = 16,
                            About = "Dr. Maha Amer is a hematologist with a strong research background in anemia and leukemia. She provides cutting-edge care in a supportive environment.",
                            Email = "maha.amer@example.com",
                            FirstName = "Maha",
                            LastName = "Amer",
                            Password = "hashedpassword16",
                            Phone = "01533445577",
                            Rate = 4.9000000000000004,
                            SpecialityId = 16
                        },
                        new
                        {
                            Id = 17,
                            About = "Dr. Ehab Hafez is a gastroenterologist known for his advanced colonoscopy techniques and management of IBS and liver disorders.",
                            Email = "ehab.hafez@example.com",
                            FirstName = "Ehab",
                            LastName = "Hafez",
                            Password = "hashedpassword17",
                            Phone = "01044556677",
                            Rate = 4.4000000000000004,
                            SpecialityId = 17
                        },
                        new
                        {
                            Id = 18,
                            About = "Dr. Rana Ashraf is a general practitioner with over 12 years of experience in family medicine, preventive care, and health education.",
                            Email = "rana.ashraf@example.com",
                            FirstName = "Rana",
                            LastName = "Ashraf",
                            Password = "hashedpassword18",
                            Phone = "01155667788",
                            Rate = 4.2999999999999998,
                            SpecialityId = 18
                        },
                        new
                        {
                            Id = 19,
                            About = "Dr. Mostafa Selim is a pulmonologist who helps patients with asthma, COPD, and chronic bronchitis breathe easier with modern therapies.",
                            Email = "mostafa.selim@example.com",
                            FirstName = "Mostafa",
                            LastName = "Selim",
                            Password = "hashedpassword19",
                            Phone = "01266778899",
                            Rate = 4.2000000000000002,
                            SpecialityId = 19
                        },
                        new
                        {
                            Id = 20,
                            About = "Dr. Reem Abdelrahman is an oncologist providing chemotherapy and personalized cancer care. She builds lasting relationships with her patients.",
                            Email = "reem.abdelrahman@example.com",
                            FirstName = "Reem",
                            LastName = "Abdelrahman",
                            Password = "hashedpassword20",
                            Phone = "01577889900",
                            Rate = 4.5999999999999996,
                            SpecialityId = 20
                        },
                        new
                        {
                            Id = 21,
                            About = "Dr. Alyaa Mansour is a radiologist with exceptional interpretation skills in MRI, CT, and ultrasound. Her quick turnaround time is highly valued.",
                            Email = "alyaa.mansour@example.com",
                            FirstName = "Alyaa",
                            LastName = "Mansour",
                            Password = "hashedpassword21",
                            Phone = "01099887766",
                            Rate = 4.4000000000000004,
                            SpecialityId = 21
                        },
                        new
                        {
                            Id = 22,
                            About = "Dr. Hany Tawfik is an anesthesiologist experienced in surgical and ICU care. His calm presence reassures patients before and during procedures.",
                            Email = "hany.tawfik@example.com",
                            FirstName = "Hany",
                            LastName = "Tawfik",
                            Password = "hashedpassword22",
                            Phone = "01188776655",
                            Rate = 4.7000000000000002,
                            SpecialityId = 22
                        },
                        new
                        {
                            Id = 23,
                            About = "Dr. Ghada Ali is a dental surgeon offering cosmetic and reconstructive dental solutions using the latest techniques and technology.",
                            Email = "ghada.ali@example.com",
                            FirstName = "Ghada",
                            LastName = "Ali",
                            Password = "hashedpassword23",
                            Phone = "01233445599",
                            Rate = 4.5,
                            SpecialityId = 23
                        },
                        new
                        {
                            Id = 24,
                            About = "Dr. Walid Gamal is a urologist specializing in kidney stone treatment and male reproductive health. He is known for his professionalism and results.",
                            Email = "walid.gamal@example.com",
                            FirstName = "Walid",
                            LastName = "Gamal",
                            Password = "hashedpassword24",
                            Phone = "01599887711",
                            Rate = 4.5999999999999996,
                            SpecialityId = 24
                        },
                        new
                        {
                            Id = 25,
                            About = "Dr. Nadine Hisham is a plastic surgeon delivering both aesthetic and reconstructive solutions tailored to each patient’s needs and desires.",
                            Email = "nadine.hisham@example.com",
                            FirstName = "Nadine",
                            LastName = "Hisham",
                            Password = "hashedpassword25",
                            Phone = "01033445588",
                            Rate = 4.7000000000000002,
                            SpecialityId = 25
                        },
                        new
                        {
                            Id = 26,
                            About = "Dr. Ayman Fathy is a vascular surgeon who treats arterial and venous diseases with minimally invasive procedures.",
                            Email = "ayman.fathy@example.com",
                            FirstName = "Ayman",
                            LastName = "Fathy",
                            Password = "hashedpassword26",
                            Phone = "01144557766",
                            Rate = 4.7999999999999998,
                            SpecialityId = 26
                        },
                        new
                        {
                            Id = 27,
                            About = "Dr. Samah Ragab is a fertility specialist offering IVF, hormonal therapies, and personalized reproductive plans for couples.",
                            Email = "samah.ragab@example.com",
                            FirstName = "Samah",
                            LastName = "Ragab",
                            Password = "hashedpassword27",
                            Phone = "01222334455",
                            Rate = 4.2999999999999998,
                            SpecialityId = 27
                        },
                        new
                        {
                            Id = 28,
                            About = "Dr. Mahmoud Salem is an experienced general practitioner offering whole-person care and long-term patient relationships.",
                            Email = "mahmoud.salem@example.com",
                            FirstName = "Mahmoud",
                            LastName = "Salem",
                            Password = "hashedpassword28",
                            Phone = "01522334455",
                            Rate = 4.5999999999999996,
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 29,
                            About = "Dr. Marwa Ashour is a dedicated pediatrician who believes in family-focused care and child development education.",
                            Email = "marwa.ashour@example.com",
                            FirstName = "Marwa",
                            LastName = "Ashour",
                            Password = "hashedpassword29",
                            Phone = "01066778899",
                            Rate = 4.4000000000000004,
                            SpecialityId = 6
                        },
                        new
                        {
                            Id = 30,
                            About = "Dr. Sherif Tarek is a critical care specialist leading ICU teams with a focus on survival, stabilization, and long-term outcomes.",
                            Email = "sherif.tarek@example.com",
                            FirstName = "Sherif",
                            LastName = "Tarek",
                            Password = "hashedpassword30",
                            Phone = "01122334455",
                            Rate = 4.9000000000000004,
                            SpecialityId = 7
                        });
                });

            modelBuilder.Entity("DAL.Models.DoctorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("AppointmentEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AppointmentStart")
                        .HasColumnType("time");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentEnd = new TimeOnly(17, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 1,
                            Day = "Monday",
                            DoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentEnd = new TimeOnly(18, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 2,
                            Day = "Tuesday",
                            DoctorId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentEnd = new TimeOnly(16, 30, 0),
                            AppointmentStart = new TimeOnly(8, 30, 0),
                            ClinicId = 3,
                            Day = "Wednesday",
                            DoctorId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentEnd = new TimeOnly(19, 0, 0),
                            AppointmentStart = new TimeOnly(11, 0, 0),
                            ClinicId = 4,
                            Day = "Thursday",
                            DoctorId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentEnd = new TimeOnly(15, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 5,
                            Day = "Friday",
                            DoctorId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentEnd = new TimeOnly(17, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 6,
                            Day = "Saturday",
                            DoctorId = 6
                        },
                        new
                        {
                            Id = 7,
                            AppointmentEnd = new TimeOnly(20, 0, 0),
                            AppointmentStart = new TimeOnly(12, 0, 0),
                            ClinicId = 7,
                            Day = "Sunday",
                            DoctorId = 7
                        },
                        new
                        {
                            Id = 8,
                            AppointmentEnd = new TimeOnly(17, 30, 0),
                            AppointmentStart = new TimeOnly(9, 30, 0),
                            ClinicId = 8,
                            Day = "Monday",
                            DoctorId = 8
                        },
                        new
                        {
                            Id = 9,
                            AppointmentEnd = new TimeOnly(18, 30, 0),
                            AppointmentStart = new TimeOnly(10, 30, 0),
                            ClinicId = 9,
                            Day = "Tuesday",
                            DoctorId = 9
                        },
                        new
                        {
                            Id = 10,
                            AppointmentEnd = new TimeOnly(14, 0, 0),
                            AppointmentStart = new TimeOnly(8, 0, 0),
                            ClinicId = 10,
                            Day = "Wednesday",
                            DoctorId = 10
                        },
                        new
                        {
                            Id = 11,
                            AppointmentEnd = new TimeOnly(21, 0, 0),
                            AppointmentStart = new TimeOnly(13, 0, 0),
                            ClinicId = 11,
                            Day = "Thursday",
                            DoctorId = 11
                        },
                        new
                        {
                            Id = 12,
                            AppointmentEnd = new TimeOnly(13, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 12,
                            Day = "Friday",
                            DoctorId = 12
                        },
                        new
                        {
                            Id = 13,
                            AppointmentEnd = new TimeOnly(16, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 13,
                            Day = "Saturday",
                            DoctorId = 13
                        },
                        new
                        {
                            Id = 14,
                            AppointmentEnd = new TimeOnly(19, 0, 0),
                            AppointmentStart = new TimeOnly(11, 0, 0),
                            ClinicId = 14,
                            Day = "Sunday",
                            DoctorId = 14
                        },
                        new
                        {
                            Id = 15,
                            AppointmentEnd = new TimeOnly(15, 30, 0),
                            AppointmentStart = new TimeOnly(8, 30, 0),
                            ClinicId = 15,
                            Day = "Monday",
                            DoctorId = 15
                        },
                        new
                        {
                            Id = 16,
                            AppointmentEnd = new TimeOnly(17, 30, 0),
                            AppointmentStart = new TimeOnly(9, 30, 0),
                            ClinicId = 16,
                            Day = "Tuesday",
                            DoctorId = 16
                        },
                        new
                        {
                            Id = 17,
                            AppointmentEnd = new TimeOnly(18, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 17,
                            Day = "Wednesday",
                            DoctorId = 17
                        },
                        new
                        {
                            Id = 18,
                            AppointmentEnd = new TimeOnly(20, 0, 0),
                            AppointmentStart = new TimeOnly(12, 0, 0),
                            ClinicId = 18,
                            Day = "Thursday",
                            DoctorId = 18
                        },
                        new
                        {
                            Id = 19,
                            AppointmentEnd = new TimeOnly(14, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 19,
                            Day = "Friday",
                            DoctorId = 19
                        },
                        new
                        {
                            Id = 20,
                            AppointmentEnd = new TimeOnly(19, 0, 0),
                            AppointmentStart = new TimeOnly(11, 0, 0),
                            ClinicId = 20,
                            Day = "Saturday",
                            DoctorId = 20
                        },
                        new
                        {
                            Id = 21,
                            AppointmentEnd = new TimeOnly(16, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 21,
                            Day = "Sunday",
                            DoctorId = 21
                        },
                        new
                        {
                            Id = 22,
                            AppointmentEnd = new TimeOnly(15, 0, 0),
                            AppointmentStart = new TimeOnly(8, 0, 0),
                            ClinicId = 22,
                            Day = "Monday",
                            DoctorId = 22
                        },
                        new
                        {
                            Id = 23,
                            AppointmentEnd = new TimeOnly(17, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 23,
                            Day = "Tuesday",
                            DoctorId = 23
                        },
                        new
                        {
                            Id = 24,
                            AppointmentEnd = new TimeOnly(21, 0, 0),
                            AppointmentStart = new TimeOnly(13, 0, 0),
                            ClinicId = 24,
                            Day = "Wednesday",
                            DoctorId = 24
                        },
                        new
                        {
                            Id = 25,
                            AppointmentEnd = new TimeOnly(18, 30, 0),
                            AppointmentStart = new TimeOnly(10, 30, 0),
                            ClinicId = 25,
                            Day = "Thursday",
                            DoctorId = 25
                        },
                        new
                        {
                            Id = 26,
                            AppointmentEnd = new TimeOnly(14, 30, 0),
                            AppointmentStart = new TimeOnly(8, 30, 0),
                            ClinicId = 26,
                            Day = "Friday",
                            DoctorId = 26
                        },
                        new
                        {
                            Id = 27,
                            AppointmentEnd = new TimeOnly(17, 0, 0),
                            AppointmentStart = new TimeOnly(9, 0, 0),
                            ClinicId = 27,
                            Day = "Saturday",
                            DoctorId = 27
                        },
                        new
                        {
                            Id = 28,
                            AppointmentEnd = new TimeOnly(18, 0, 0),
                            AppointmentStart = new TimeOnly(12, 0, 0),
                            ClinicId = 28,
                            Day = "Sunday",
                            DoctorId = 28
                        },
                        new
                        {
                            Id = 29,
                            AppointmentEnd = new TimeOnly(19, 0, 0),
                            AppointmentStart = new TimeOnly(11, 0, 0),
                            ClinicId = 29,
                            Day = "Monday",
                            DoctorId = 29
                        },
                        new
                        {
                            Id = 30,
                            AppointmentEnd = new TimeOnly(16, 0, 0),
                            AppointmentStart = new TimeOnly(10, 0, 0),
                            ClinicId = 30,
                            Day = "Tuesday",
                            DoctorId = 30
                        });
                });

            modelBuilder.Entity("DAL.Models.Governate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الأسكندرية"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            Id = 5,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            Id = 6,
                            Name = "البحيرة"
                        },
                        new
                        {
                            Id = 7,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 8,
                            Name = "الغربية"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الإسماعلية"
                        },
                        new
                        {
                            Id = 10,
                            Name = "المنوفية"
                        },
                        new
                        {
                            Id = 11,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 12,
                            Name = "القليوبية"
                        },
                        new
                        {
                            Id = 13,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            Id = 14,
                            Name = "السويس"
                        },
                        new
                        {
                            Id = 15,
                            Name = "اسوان"
                        },
                        new
                        {
                            Id = 16,
                            Name = "اسيوط"
                        },
                        new
                        {
                            Id = 17,
                            Name = "بني سويف"
                        },
                        new
                        {
                            Id = 18,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            Id = 19,
                            Name = "دمياط"
                        },
                        new
                        {
                            Id = 20,
                            Name = "الشرقية"
                        },
                        new
                        {
                            Id = 21,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            Id = 22,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            Id = 23,
                            Name = "مطروح"
                        },
                        new
                        {
                            Id = 24,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 25,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 26,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            Id = 27,
                            Name = "سوهاج"
                        });
                });

            modelBuilder.Entity("DAL.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("GovernateId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("GovernateId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            GovernateId = 1,
                            PostalCode = "10023",
                            Street = "45 Talaat Harb St."
                        },
                        new
                        {
                            Id = 2,
                            CityId = 9,
                            GovernateId = 2,
                            PostalCode = "10154",
                            Street = "88 Kasr El Nile St."
                        },
                        new
                        {
                            Id = 3,
                            CityId = 12,
                            GovernateId = 3,
                            PostalCode = "10276",
                            Street = "29 Abbas El Akkad St."
                        },
                        new
                        {
                            Id = 4,
                            CityId = 16,
                            GovernateId = 4,
                            PostalCode = "10322",
                            Street = "77 El Nasr Rd."
                        },
                        new
                        {
                            Id = 5,
                            CityId = 19,
                            GovernateId = 5,
                            PostalCode = "10498",
                            Street = "15 El Merghany St."
                        },
                        new
                        {
                            Id = 6,
                            CityId = 22,
                            GovernateId = 6,
                            PostalCode = "10531",
                            Street = "61 Al Haram St."
                        },
                        new
                        {
                            Id = 7,
                            CityId = 25,
                            GovernateId = 7,
                            PostalCode = "10647",
                            Street = "94 Faisal St."
                        },
                        new
                        {
                            Id = 8,
                            CityId = 28,
                            GovernateId = 8,
                            PostalCode = "10782",
                            Street = "36 October 6th St."
                        },
                        new
                        {
                            Id = 9,
                            CityId = 31,
                            GovernateId = 9,
                            PostalCode = "10859",
                            Street = "103 Ahmed Orabi St."
                        },
                        new
                        {
                            Id = 10,
                            CityId = 34,
                            GovernateId = 10,
                            PostalCode = "10964",
                            Street = "20 Sudan St."
                        },
                        new
                        {
                            Id = 11,
                            CityId = 37,
                            GovernateId = 11,
                            PostalCode = "11035",
                            Street = "11 Shubra St."
                        },
                        new
                        {
                            Id = 12,
                            CityId = 38,
                            GovernateId = 11,
                            PostalCode = "11109",
                            Street = "81 Ain Shams St."
                        },
                        new
                        {
                            Id = 13,
                            CityId = 40,
                            GovernateId = 12,
                            PostalCode = "11243",
                            Street = "38 Al Moqatam St."
                        },
                        new
                        {
                            Id = 14,
                            CityId = 41,
                            GovernateId = 12,
                            PostalCode = "11356",
                            Street = "52 Naguib Mahfouz St."
                        },
                        new
                        {
                            Id = 15,
                            CityId = 4,
                            GovernateId = 1,
                            PostalCode = "11477",
                            Street = "66 El Hegaz St."
                        },
                        new
                        {
                            Id = 16,
                            CityId = 5,
                            GovernateId = 1,
                            PostalCode = "11588",
                            Street = "91 Salah Salem St."
                        },
                        new
                        {
                            Id = 17,
                            CityId = 6,
                            GovernateId = 1,
                            PostalCode = "11642",
                            Street = "27 El Khalifa El Maamoun St."
                        },
                        new
                        {
                            Id = 18,
                            CityId = 13,
                            GovernateId = 3,
                            PostalCode = "11793",
                            Street = "74 Al Azhar St."
                        },
                        new
                        {
                            Id = 19,
                            CityId = 14,
                            GovernateId = 3,
                            PostalCode = "11834",
                            Street = "59 Mohamed Mahmoud St."
                        },
                        new
                        {
                            Id = 20,
                            CityId = 17,
                            GovernateId = 4,
                            PostalCode = "11921",
                            Street = "35 Al Mokattam Corniche"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 18,
                            GovernateId = 4,
                            PostalCode = "12015",
                            Street = "14 Saad Zaghloul St."
                        },
                        new
                        {
                            Id = 22,
                            CityId = 20,
                            GovernateId = 5,
                            PostalCode = "12126",
                            Street = "109 Al Nozha St."
                        },
                        new
                        {
                            Id = 23,
                            CityId = 21,
                            GovernateId = 5,
                            PostalCode = "12274",
                            Street = "63 Makram Ebeid St."
                        },
                        new
                        {
                            Id = 24,
                            CityId = 23,
                            GovernateId = 6,
                            PostalCode = "12333",
                            Street = "79 El Orouba St."
                        },
                        new
                        {
                            Id = 25,
                            CityId = 24,
                            GovernateId = 6,
                            PostalCode = "12488",
                            Street = "32 Cleopatra St."
                        },
                        new
                        {
                            Id = 26,
                            CityId = 27,
                            GovernateId = 7,
                            PostalCode = "12577",
                            Street = "48 Al Thawra St."
                        },
                        new
                        {
                            Id = 27,
                            CityId = 28,
                            GovernateId = 8,
                            PostalCode = "12644",
                            Street = "17 Al Montazah St."
                        },
                        new
                        {
                            Id = 28,
                            CityId = 2,
                            GovernateId = 1,
                            PostalCode = "12753",
                            Street = "70 Ramses St."
                        },
                        new
                        {
                            Id = 29,
                            CityId = 3,
                            GovernateId = 1,
                            PostalCode = "12819",
                            Street = "97 Gomhoria St."
                        },
                        new
                        {
                            Id = 30,
                            CityId = 8,
                            GovernateId = 2,
                            PostalCode = "12902",
                            Street = "22 Port Said St."
                        });
                });

            modelBuilder.Entity("DAL.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("passwordResetTokens");
                });

            modelBuilder.Entity("DAL.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DAL.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DAL.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "أخصائي حساسية/مناعة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "أخصائي تخدير"
                        },
                        new
                        {
                            Id = 3,
                            Name = "أخصائي قلب"
                        },
                        new
                        {
                            Id = 4,
                            Name = "أخصائي جلدية"
                        },
                        new
                        {
                            Id = 5,
                            Name = "أخصائي غدد صماء"
                        },
                        new
                        {
                            Id = 6,
                            Name = "أخصائي جهاز هضمي"
                        },
                        new
                        {
                            Id = 7,
                            Name = "طبيب عام"
                        },
                        new
                        {
                            Id = 8,
                            Name = "أخصائي طب كبار السن"
                        },
                        new
                        {
                            Id = 9,
                            Name = "أخصائي دم"
                        },
                        new
                        {
                            Id = 10,
                            Name = "أخصائي أمراض معدية"
                        },
                        new
                        {
                            Id = 11,
                            Name = "طبيب باطنية"
                        },
                        new
                        {
                            Id = 12,
                            Name = "أخصائي كلى"
                        },
                        new
                        {
                            Id = 13,
                            Name = "أخصائي أعصاب"
                        },
                        new
                        {
                            Id = 14,
                            Name = "أخصائي نساء وتوليد"
                        },
                        new
                        {
                            Id = 15,
                            Name = "أخصائي أورام"
                        },
                        new
                        {
                            Id = 16,
                            Name = "أخصائي عيون"
                        },
                        new
                        {
                            Id = 17,
                            Name = "جراح عظام"
                        },
                        new
                        {
                            Id = 18,
                            Name = "أخصائي أنف وأذن وحنجرة"
                        },
                        new
                        {
                            Id = 19,
                            Name = "أخصائي أمراض"
                        },
                        new
                        {
                            Id = 20,
                            Name = "أخصائي أطفال"
                        },
                        new
                        {
                            Id = 21,
                            Name = "جراح تجميل"
                        },
                        new
                        {
                            Id = 22,
                            Name = "أخصائي نفسية"
                        },
                        new
                        {
                            Id = 23,
                            Name = "أخصائي صدر"
                        },
                        new
                        {
                            Id = 24,
                            Name = "أخصائي أشعة"
                        },
                        new
                        {
                            Id = 25,
                            Name = "أخصائي روماتيزم"
                        },
                        new
                        {
                            Id = 26,
                            Name = "جراح عام"
                        },
                        new
                        {
                            Id = 27,
                            Name = "أخصائي مسالك بولية"
                        });
                });

            modelBuilder.Entity("DAL.Models.Appointment", b =>
                {
                    b.HasOne("DAL.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.HasOne("DAL.Models.Governate", "Governate")
                        .WithMany()
                        .HasForeignKey("GovernateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("DAL.Models.Clinic", b =>
                {
                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Location");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.HasOne("DAL.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DAL.Models.DoctorAvailability", b =>
                {
                    b.HasOne("DAL.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DAL.Models.Location", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Governate", "Governate")
                        .WithMany()
                        .HasForeignKey("GovernateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("DAL.Models.Payment", b =>
                {
                    b.HasOne("DAL.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DAL.Models.Doctor", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Clinics");
                });
#pragma warning restore 612, 618
        }
    }
}
